server:
  forward-headers-strategy: framework
  port: 8765
  error:
    include-message: always

context-path: /api/v1

spring:
  jackson:
    time-zone: Europe/Moscow
  cloud:
    loadbalancer:
      cache:
        enabled: false
    gateway:
      default-filters:
        - StripPrefix=1
        - RewritePath=/(?<path>.*), ${context-path}/$\{path}
      routes:
        - id: auth-openapi
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/v3/api-docs, /auth-service/swagger-ui/**

        - id: user-openapi
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs, /user-service/swagger-ui/**

        - id: movie-openapi
          uri: lb://movie-service
          predicates:
            - Path=/movie-service/v3/api-docs, /movie-service/swagger-ui/**

        - id: file-openapi
          uri: lb://file-service
          predicates:
            - Path=/file-service/v3/api-docs, /file-service/swagger-ui/**

        - id: session-openapi
          uri: lb://session-service
          predicates:
            - Path=/session-service/v3/api-docs, /session-service/swagger-ui/**

        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/auth/login, /auth-service/token/validate

        - id: admin
          uri: lb://user-service
          predicates:
            - Path=/user-service/users/register, /user-service/users/change-role
          filters:
            - AuthenticationFilter
        
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user-service/users/upload-avatar, /user-service/users/change-email
          filters:
            - AuthenticationFilter

        - id: files
          uri: lb://file-service
          predicates:
            - Path=/file-service/files/download/**

        - id: movie
          uri: lb://movie-service
          predicates:
            - Path=/movie-service/movie/**, /movie-service/movie/movies-by-genre/**, /movie-service/movie/popular-movies/**, /movie-service/movie/genres-list
          filters:
            - AuthenticationFilter

        - id: session
          uri: lb://session-service
          predicates:
            - Path=/session-service/session/current, /session-service/session/exit, /session-service/session/create, /session-service/session/join/**, /session-service/session/delete/**, /session-service/session/add-movie, /session-service/session/liked-movies, /session-service/session/matched-movies 
          filters:
            - AuthenticationFilter




eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

reactive:
  feign:
    circuit:
      breaker:
        enabled: false

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: trace
    io.github.resilience4j: debug


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

